### ISSUE TITLE
Query execution exception?

### ISSUE THREAD

**Issue by kalwar** [jettro/elasticsearch-gui#102]
When I click on the "Last" button of the paging component I am getting following exception/error message:

[query_phase_execution_exception] Result window is too large, from + size must be less than or equal to: [10000] but was [45120]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.

Where do I change this: "index.max_result_window"?

**Comment by jettro** [comment]
This is an error coming from elasticsearch, cannot really fix this in the tool. More information about setting index settings can be found here: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-update-settings.html
