### ISSUE TITLE
Fix wrapping of long text content when showing indexes

### ISSUE THREAD

**Issue by arruor** [jettro/elasticsearch-gui#103]
For wrapping of long text when showing indexes names included in snapshot(s) in snapshot module.

When there are a lot of indexes included in snapshot and/or there are an index(es) with log name(s) - table content breaks page design. Example: `["index_name","index_name","index_name","index_name","index_name","index_name","index_name","index_name","index_name","index_name","index_name","index_name","index_name","index_name","index_name","index_name","index_name","index_name","index_name","index_name","index_name","index_name","index_name"]`

Possible solutions:
* Use some word wrap CSS tricks
* Display content with fixed width and show full index list on hover (mouseIn, mounseOut events)
* Split index list elements by space (or other wrapping symbol)

**Comment by jettro** [comment]
![screen shot 2016-05-31 at 08 40 17](https://cloud.githubusercontent.com/assets/149687/15665438/772e75d4-270b-11e6-8f62-a8682c905aae.png)
I do not see the problem, check my screenshot, maybe you see something else?
