### ISSUE TITLE
Feature request: add text input field to execute raw json query bypassing the query builder

### ISSUE THREAD

**Issue by manioc2015** [jettro/elasticsearch-gui#105]
I think it would be useful to have the ability to execute a raw json elasticsearch query by copy/pasting whatever the json is as opposed to being forced to use the tedious query builder.

Does anyone else agree?

**Comment by jettro** [comment]
The goal for this tool has always been to provide a mechanism for people that do not know the query syntax to be able to query elastic and to learn about the query syntax by looking at the resulting query.

To be able to copy paste a son query makes me wonder:
- What is the additionl use for the tool?
- What is the next step, help with writing the son query? To start supporting the query syntax is an incredible effort.

So please tell me a bit more about what you expect from supporting copy-paste json queries.
