### ISSUE TITLE
indexes, types, and fields are not visible/selectable in queries tab 

### ISSUE THREAD

**Issue by arnaud71** [jettro/elasticsearch-gui#106]
Hi,

indexes, types, and field are not visible selectable in queries tab while I can do search from search tab, select the index in configuration menu, and also find the field type in Inspect tab (see the screen shot)

![capture d ecran 2016-06-22 a 15 37 57](https://cloud.githubusercontent.com/assets/650826/16268602/5c92fd9a-388f-11e6-947f-9c09466e6e00.png)

my elasticsearch instance is local:9200 (all on my computer) and I use version 2.3.3 of elasticsearch

thanks for this great soft,
regards

ps: I tried also to change the http.cors.enabled but same local domain so no better result

**Comment by jettro** [comment]
Strange, can you check if there is a log in your browser? It should be working fine.

**Comment by arnaud71** [comment]
sorry, no log, in my 3 browsers (i'm on mac). 
I'm new with elasticsearch, but head, kibana seems to works and some parts of your nice plugin too.
I'll try same config on linux too, if you haven't other idea.

thanks

**Comment by jettro** [comment]
Hmm strange, I am on the Mac as well. Can you give me the output of the following command:
`curl "localhost:9200/_cat/indices?v"`

**Comment by arnaud71** [comment]
off course:

$ curl "localhost:9200/_cat/indices?v"
health status index   pri rep docs.count docs.deleted store.size pri.store.size
green  open   .kibana   1   1          2            0     12.9kb          7.7kb
green  open   medline   5   1        100            0      657kb        325.7kb

**Comment by jettro** [comment]
Trying to com up with ideas, did you by any change filter out an index using the settings button near the name of the cluster in the top right corner?

**Comment by arnaud71** [comment]
I did it afterwards, and I just cleaned after your comment, but same behaviour.

**Comment by jettro** [comment]
I just started a clean elasticsearch instance and installed the plugin, you just found a bug. It is not working for me as well. So I need to fix this. Sorry about that.

**Comment by arnaud71** [comment]
don't worry, let me know when I can help you to test.

**Comment by jettro** [comment]
I think I squashed the bug, if you reinstall the plugin it should work. There is still one nasty thing, if you refresh your browser with the query tab open it will not work. Then you have to click one of the other tabs and go back. There is a timing problem with initialising the service and calling the service. Will fix this later on.

**Comment by arnaud71** [comment]
that's really nice, for what I needed. Thank you very much for your fast correction
