### ISSUE TITLE
ALERTunknown error

### ISSUE THREAD

**Issue by webattitude** [jettro/elasticsearch-gui#108]
Hi, everything is empty (I mean no index showing) and following message appears constantly : 
```ALERTunknown error```

-Tom

**Comment by jettro** [comment]
This usually means there is no connection to elasticsearch, but I agree the message could be a lot clearer.

**Comment by webattitude** [comment]
plugin is trying to connect to localhost... not to the server url I specified

**Comment by jettro** [comment]
I think I fixed it, there was a bug with the loading of the server url. It looked like the url was ok, but actually it was just using localhost. This is fixed. The error is a hard one to tackle. For now I changed the error message.
