### ISSUE TITLE
ERROR: Unknown plugin jettro/elasticsearch-gui

### ISSUE THREAD

**Issue by lefuturiste** [jettro/elasticsearch-gui#112]
`bin/elasticsearch-plugin install jettro/elasticsearch-gui`

ERROR: Unknown plugin jettro/elasticsearch-gui

**Comment by jettro** [comment]
Not sure on which version you are trying to do this, but this plugin is not really active any longer. It was created for elastic 1.x. It will not work as a plugin for more recent versions. It was possible to use it stand alone, but even that is not something I have tested for the last 2 years or so

**Comment by lefuturiste** [comment]
Ok no problems
