### ISSUE TITLE
http://www.gridshore.nl/esgui not usable

### ISSUE THREAD

**Issue by danyill** [jettro/elasticsearch-gui#94]
http://www.gridshore.nl/esgui just produced "unknown errors" when attempting to test.

**Comment by jettro** [comment]
Can you elaborate a bit on what you are trying to do? What version of elasticsearch are you running? Do you run a localhost installation? Did you add the cors settings? Maybe you can check the browser developer console and check for errors?

**Comment by danyill** [comment]
Sorry was a little frustrated at the time. I expected I would be able to test your plugin by going to http://www.gridshore.nl/esgui but it seems that it doesn't have a connection with an elastic search server. Not sure if this is what was intended. At the same time I didn't have it working on my local machine although this is not fixed. Having said that, no matter what I do to the cors setting I can't access the webpage of the plugin from my local machine when elasticsearch is running within a VM but I have the  impression this might not be possible in elasticsearch 2.1 onward?

![snapshot2-esgui](https://cloud.githubusercontent.com/assets/674783/11768647/968e3a16-a238-11e5-8cce-508f67b53139.png)

**Comment by jettro** [comment]
I have it running with slightly different settings than I have documented, need to update it:

```
http.cors.enabled: true
http.cors.allow-origin: /https?:\/\/(localhost(:[0-9]+)?)?(www.gridshore.nl)?/
```
