### ISSUE TITLE
Field, Value and Terms

### ISSUE THREAD

**Issue by kalwar** [jettro/elasticsearch-gui#97]
Why the field, values and terms are not shown when we click on the "Show Terms"
in the simple search?

**Comment by jettro** [comment]
Often this has to do with the indexes that are available. Sometimes the structure gives a problem, could also be a combination of indexes. If you are using multiple indexes did you try to limit the ones that are included using the top screen filter box? If you give me an idea about the structure that is giving problems I can try to find the issue. Also please let me know the version of elastic that you are using.

**Comment by kalwar** [comment]
Thanks for your kind response. I am using elasticsearch 1.7. You are right ...  I am using multiple indices. I don't understand what do you mean by "top screen filter box?" Do you mean the dialog box where we can include or exclude the indices? I have included the indices that I am using inside this dialog box.

Attached is the screenshot that shows just blank (i.e. no field, value and terms). 


![screenshot from 2016-03-07 15-00-10](https://cloud.githubusercontent.com/assets/2051126/13594198/00aa542e-e50b-11e5-8632-9b4a8c23c22e.png)

**Comment by jettro** [comment]
If you are on 1.7 you cannot use the latest version of the plugin. This
version works only with 2.0 for a lot of the features. Best to checkout an
older tag:
https://github.com/jettro/elasticsearch-gui/releases/tag/1.3.0

Maybe you can check the browser console for more specifics.

The filter box is the config dialog that you can reach from the top right
part of the screen by clicking on the "cog".

Hope that helps



On Tue, Mar 8, 2016 at 7:54 AM, AppKeto <notifications@github.com> wrote:

> Thanks for your kind response. I am using elasticsearch 1.7. You are right
> ... I am using multiple indices. I don't understand what do you mean by
> "top screen filter box?" Do you mean the dialog box where we can include or
> exclude the indices? I have included the indices that I am using inside
> this dialog box.
>
> Attached is the screenshot that shows just blank (i.e. no field, value and
> terms).
>
> [image: screenshot from 2016-03-07 15-00-10]
> <https://cloud.githubusercontent.com/assets/2051126/13594198/00aa542e-e50b-11e5-8632-9b4a8c23c22e.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jettro/elasticsearch-gui/issues/97#issuecomment-193632918>
> .
>



-- 
Jettro Coenradie
http://www.gridshore.nl

**Comment by kalwar** [comment]
Thanks for your response. 
Works like charm in ES 2.0.
